services:
  flutter-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: f_ets_web:prod
    container_name: f_ets_web
    ports:
      - '8081:8080'
    restart: unless-stopped

  flutter-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: f_ets_web:dev
    container_name: f_ets_dev
    profiles:
      - dev
    volumes:
      - .:/app
      - flutter_pub:/app/.dart_tool
      - flutter_cache:/opt/flutter
    ports:
      - '5001:5000'
    restart: unless-stopped

volumes:
  flutter_pub:
  flutter_cache:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: f_ets_br0
